# Generated by Django 4.0.6 on 2022-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='유저이름')),
                ('score', models.IntegerField(default=0, verbose_name='총 점수')),
            ],
        ),
    ]
