# Generated by Django 4.0.6 on 2022-07-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='유저이름')),
                ('score', models.IntegerField(default=0, verbose_name='총 점수')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=31, verbose_name='게임 아이디')),
                ('user1_num', models.IntegerField(verbose_name='유저1 선택숫자')),
                ('user2_num', models.IntegerField(verbose_name='유저2 선택숫자')),
                ('result', models.CharField(max_length=63, verbose_name='게임 결과')),
                ('rule', models.CharField(max_length=63, verbose_name='게임 룰')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user1', to='games.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user2', to='games.user')),
            ],
        ),
    ]
