# Generated by Django 4.0.6 on 2022-07-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user1', to='users.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user2', to='users.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
