# Generated by Django 4.0.6 on 2022-07-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_user1_alter_game_user2_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
    ]
